package com.cir.cirback.controllers;

import java.util.HashSet;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import com.cir.cirback.dtos.RoleDTO;
import com.cir.cirback.dtos.UserDTO;
import com.cir.cirback.dtos.UserMapper;
import com.cir.cirback.entities.Role;
import com.cir.cirback.entities.User;
import com.cir.cirback.repositories.RoleRepository;
import com.cir.cirback.repositories.UserRepository;

@RestController // This means that this class is a Controller
@CrossOrigin
@RequestMapping(path="/api/user") // This means URL's start with /api (after Application path)
public class UserController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private UserRepository userRepository;
  @Autowired
  private RoleRepository roleRepository;
  @Autowired
  private UserMapper userMapper;

  	

	@GetMapping(path="/getall")
	public @ResponseBody ResponseEntity<Iterable<UserDTO>> getAllUsers() {
	    // This returns a JSON or XML with the users
	    return new ResponseEntity(
	    		userRepository.findAll()
	    			.stream()
	    			.map(userMapper::userToUserDto)
	    			.collect(Collectors.toList()),
	    		HttpStatus.OK);
	}
  
	@GetMapping("/get/{id}")
	public @ResponseBody ResponseEntity<?> getUser(@PathVariable(name = "id") int id) {
		
		 Optional<User> userOptional = userRepository.findById(id);
		
		if (userOptional.isPresent()) {
	        UserDTO userDTO = userMapper.userToUserDto(userOptional.get());
	        return new ResponseEntity<>(userDTO, HttpStatus.OK);
	    } else {
	        return new ResponseEntity<>("User not found", HttpStatus.NOT_FOUND);
	    }
	}
	
	@PostMapping(path="/add") // Map ONLY POST Requests
  	public @ResponseBody ResponseEntity<String> addNewUser (
		  @RequestBody User user
      ) {
	    // @ResponseBody means the returned String is the response, not a view name
	    // @RequestParam means it is a parameter from the GET or POST request
		User n = user;
	
	    Set<Role> roles = new HashSet<>();
	    Role role_admin = roleRepository.findByRole("administrador").get();
	    roles.add(role_admin);
	    n.setRoles(roles);
	    
	    userRepository.save(n);
	
	    return new ResponseEntity("User saved", HttpStatus.OK);
	}
	
	@DeleteMapping("/delete/{id}")
	public @ResponseBody ResponseEntity<String> deleteUser(@PathVariable(name = "id") int id) {
		userRepository.deleteById(id);
		return new ResponseEntity("User Deleted", HttpStatus.OK);
	}
	
	@PutMapping(path="/update/{id}") // Map ONLY PUT Requests
	  public @ResponseBody ResponseEntity<String> modifyUser (
			  @PathVariable(name = "id") int id,
			  @RequestBody User user
	      ) {
	    // @ResponseBody means the returned String is the response, not a view name
	    // @RequestParam means it is a parameter from the GET or POST request
		
		if (!userRepository.existsById(id)) {
			return new ResponseEntity("User does not exist", HttpStatus.NOT_FOUND);
		}
		
		User n = userRepository.findById(id).get();
		if (!n.getUsername().equals(user.getUsername())) {
			return new ResponseEntity("Username does not match", HttpStatus.BAD_REQUEST);
		}
		

		n.setEmail(user.getEmail());
		n.setPassword(user.getPassword());
		n.setName(user.getName());
		n.setSurname(user.getSurname());
		n.setDni(user.getDni());
		
	    //Set<Role> roles = new HashSet<>();
	    //Role role_admin = roleRepository.findByRole("administrador").get();
	    //roles.add(role_admin);
	    n.setRoles(user.getRoles());
	    
	    userRepository.save(n);
	    return new ResponseEntity("User updated", HttpStatus.OK);
	  }
}